### ISSUE TITLE
Rain widget missing 

### ISSUE THREAD

**Issue by LastHope84** [darkmoonight/Projects#1]
I've swapped the app from the PlayStore one to the one in the telegram channel and the possibility to add its widget is suddenly gone

**Comment by Leonavichus** [comment]
This is strange, can you tell me which phone and Android version you have?

**Comment by LastHope84** [comment]
Poco m6 pro
A14

**Comment by Leonavichus** [comment]
[#154](https://github.com/darkmoonight/Rain/issues/154)
